#!/bin/bash
mkdir welcome welcom[D[D[D[D[D[D/[C[C[C[C[D[D[D[Dwelcome/to /welcome/to/school
[D[D[D[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C-p[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[[C[C[C[C[C[C[C[welcome/to/school
